name: Project CICD
run-name: ${{ github.actor }} - CICD
on: [push]

jobs:
  #
  # --- Code-linting
  lint-code:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      # Install Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      # Install python dependencies
      - name: Install dependencies
        run: |
          make requirements
          make pre-commit-install
          make lint
